Updated README.md file
pieces-app/example-ts pull request #1
Opened 2023-11-03 19:15 UTC by Sophyia7

I updated the README.md file by fixing spelling errors and adding missing images.

2023-11-03 19:33 UTC, jordan-pieces requested changes
my mistake on the /assets vs Asset difference, i could've been more clear about the importance in their differences. Asset is a type, while Assets[<Asset>] is an array of your assets.

2023-11-03 19:33 UTC, jordan-pieces commented on README.md
> -### `/assets/create`
this one is okay to stay like this: `/assets/create`

2023-11-03 19:33 UTC, jordan-pieces commented on README.md
> -### `/assets/create`
correct: /assets/create
incorrect: Assets/create

2023-11-03 19:33 UTC, jordan-pieces commented on README.md
> +![Console Output](image.png)
i created an assets folder that i will be merging in, but you can just create one as well and put it at the root directory of the project

2023-11-03 19:33 UTC, jordan-pieces commented on README.md
> -## Getting Started with `/asset` + `/assets`
Correct: Asset or /assets
Incorrect: Assets or /asset

2023-11-03 19:33 UTC, jordan-pieces commented on README.md
> -- Adding a UI to view multiple snippets from `/assets`
this is okay as /assets

2023-11-03 19:52 UTC, Sophyia7 commented on README.md
> -- Adding a UI to view multiple snippets from `/assets`
@jordan-pieces I have made the changes.

2023-11-07 22:18 UTC, jordan-pieces approved these changes
looking good thank you @Sophyia7 !

2023-11-07 22:18 UTC, merged